// Content script for DGA Detection extension
// Shows warning overlay when DGA domain is detected

let warningShown = false;

// Create warning overlay
function showWarning(domain, confidence) {
  if (warningShown) return;
  warningShown = true;

  const overlay = document.createElement('div');
  overlay.id = 'dga-warning-overlay';
  overlay.innerHTML = `
    <div style="
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.85);
      z-index: 2147483647;
      display: flex;
      align-items: center;
      justify-content: center;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    ">
      <div style="
        background: white;
        border-radius: 12px;
        padding: 32px;
        max-width: 500px;
        text-align: center;
        box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
      ">
        <div style="
          width: 64px;
          height: 64px;
          background: #fef2f2;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          margin: 0 auto 16px;
        ">
          <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="#ef4444" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>
            <line x1="12" y1="9" x2="12" y2="13"/>
            <line x1="12" y1="17" x2="12.01" y2="17"/>
          </svg>
        </div>

        <h1 style="
          color: #dc2626;
          font-size: 24px;
          font-weight: 700;
          margin: 0 0 8px;
        ">Potential Malicious Domain Detected</h1>

        <p style="
          color: #6b7280;
          font-size: 14px;
          margin: 0 0 16px;
        ">
          This domain appears to be generated by a Domain Generation Algorithm (DGA),
          commonly used by malware and botnets.
        </p>

        <div style="
          background: #fef2f2;
          border: 1px solid #fecaca;
          border-radius: 8px;
          padding: 12px;
          margin-bottom: 16px;
        ">
          <p style="
            color: #991b1b;
            font-size: 14px;
            margin: 0 0 4px;
            font-weight: 600;
          ">Domain: ${domain}</p>
          <p style="
            color: #b91c1c;
            font-size: 12px;
            margin: 0;
          ">Confidence: ${(confidence * 100).toFixed(1)}%</p>
        </div>

        <div style="display: flex; gap: 12px; justify-content: center;">
          <button id="dga-go-back" style="
            background: #dc2626;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 8px;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            transition: background 0.2s;
          ">Go Back to Safety</button>

          <button id="dga-continue" style="
            background: white;
            color: #6b7280;
            border: 1px solid #d1d5db;
            padding: 12px 24px;
            border-radius: 8px;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s;
          ">Continue Anyway</button>
        </div>

        <p style="
          color: #9ca3af;
          font-size: 11px;
          margin: 16px 0 0;
        ">Protected by DGA Detector Extension</p>
      </div>
    </div>
  `;

  document.body.appendChild(overlay);

  // Handle button clicks
  document.getElementById('dga-go-back').addEventListener('click', () => {
    window.history.back();
    if (window.history.length <= 1) {
      window.close();
    }
  });

  document.getElementById('dga-continue').addEventListener('click', () => {
    overlay.remove();
    warningShown = false;
  });

  // Hover effects
  const backBtn = document.getElementById('dga-go-back');
  backBtn.addEventListener('mouseenter', () => {
    backBtn.style.background = '#b91c1c';
  });
  backBtn.addEventListener('mouseleave', () => {
    backBtn.style.background = '#dc2626';
  });

  const continueBtn = document.getElementById('dga-continue');
  continueBtn.addEventListener('mouseenter', () => {
    continueBtn.style.background = '#f3f4f6';
  });
  continueBtn.addEventListener('mouseleave', () => {
    continueBtn.style.background = 'white';
  });
}

// Listen for messages from background script
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === 'DGA_DETECTED') {
    showWarning(message.domain, message.result.confidence);
  }
});

// Also check on page load
window.addEventListener('load', () => {
  // Remove any existing overlay on navigation
  const existing = document.getElementById('dga-warning-overlay');
  if (existing) {
    existing.remove();
    warningShown = false;
  }
});
